spring.application.name=customer-service
server.port=8000


eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

#If config-server url has fixed URL 
#spring.config.import=optional:configserver:http://localhost:8888
#If config server url is service discovery based 	
spring.config.import=optional:configserver:
spring.cloud.config.discovery.enabled=true
spring.cloud.config.discovery.service-id=config-server